/*Cart Actions*/
export const CART_ADD_ITEM    = "CART_ADD_ITEM";
export const CART_DELETE_ITEM = "CART_DELETE_ITEM";

export const PREPARE_FOR_ORDER = "PREPARE_FOR_ORDER";

export const ORDER_PLACE_START   = "ORDER_PLACE_START";
export const ORDER_PLACE_SUCCESS = "ORDER_PLACE_SUCCESS";
export const ORDER_PLACE_FAILED  = "ORDER_PLACE_FAILED";

export const ORDER_FETCH_START   = "ORDER_FETCH_START";
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS";
export const ORDER_FETCH_FAILED  = "ORDER_FETCH_FAILED";

export const AUTH_START       = "AUTH_START";
export const AUTH_SUCCESS     = "AUTH_SUCCESS";
export const AUTH_FAILED      = "AUTH_FAILED";
export const AUTH_LOGOUT      = "AUTH_LOGOUT";